name: WebDriver

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Cargo test
        working-directory: ./src-tauri
        run: cargo test

      - name: Cargo build
        working-directory: ./src-tauri
        run: cargo build --release
