name: Moras CI

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Tauri dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install -y libgtk-3-dev libayatana-appindicator3-dev libwebkit2gtk-4.0-dev webkit2gtk-driver xvfb

      - name: Cache Cargo packages
        uses: actions/cache@v3
        with:
          path: |
           ~/.cargo
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Cargo test
        working-directory: ./src-tauri
        run: cargo test

      - name: Cargo build
        working-directory: ./src-tauri
        run: cargo build --release
