name: Build&Test

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Tauri dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install -y libgtk-3-dev libayatana-appindicator3-dev libwebkit2gtk-4.0-dev webkit2gtk-driver xvfb

      - name: Cargo test
        working-directory: ./src-tauri
        run: cargo test

      - name: Cargo build
        working-directory: ./src-tauri
        run: cargo build --release
